# Generated by Django 6.1.1 on 2026-09-29 23:51

import contas.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('corretor', 'Corretor'), ('imobiliaria', 'Imobiliária')], max_length=12)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('creci', models.CharField(blank=True, default='', max_length=64)),
                ('razao_social', models.CharField(blank=True, default='', max_length=255)),
                ('cnpj', models.CharField(blank=True, default='', max_length=14)),
                ('responsavel', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', contas.models.ContaManager()),
            ],
        ),
    ]
