# Generated by Django 6.1.1 on 2026-09-30 11:43

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_isolamento_da_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='criada_em',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conta',
            name='pesquisas_gratis_usadas',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
