# Generated by Django 6.1.1 on 2026-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_cota_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='mes_da_cota',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='pesquisas_mes_usadas',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='plano',
            field=models.CharField(blank=True, db_default='', default='', max_length=8),
        ),
    ]
