# Generated by Django 6.1.1 on 2026-09-30 12:47

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _executar(schema_editor, sql):
    schema_editor.execute(sql)


def aplicar_isolamento_do_credito(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        """
        GRANT SELECT, INSERT, UPDATE, DELETE
            ON TABLE public.contas_credito
            TO rondimob_web, rondimob_worker
        """,
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.contas_credito ENABLE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.contas_credito FORCE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "DROP POLICY IF EXISTS conta_isola ON public.contas_credito",
    )
    _executar(
        schema_editor,
        """
        CREATE POLICY conta_isola ON public.contas_credito
        USING (conta_id::text = current_setting('app.conta_id', true))
        WITH CHECK (conta_id::text = current_setting('app.conta_id', true))
        """,
    )


def reverter_isolamento_do_credito(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        "DROP POLICY IF EXISTS conta_isola ON public.contas_credito",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.contas_credito NO FORCE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.contas_credito DISABLE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "REVOKE ALL ON TABLE public.contas_credito FROM rondimob_web, rondimob_worker",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_plano_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restante', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            aplicar_isolamento_do_credito,
            reverter_isolamento_do_credito,
        ),
    ]
