# Generated by Django 6.1.1 on 2026-09-30 16:02

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _executar(schema_editor, sql):
    schema_editor.execute(sql)


def aplicar_isolamento_do_radar(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        """
        GRANT SELECT, INSERT, UPDATE, DELETE
            ON TABLE public.radares_radar
            TO rondimob_web, rondimob_worker
        """,
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.radares_radar ENABLE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.radares_radar FORCE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "DROP POLICY IF EXISTS conta_isola ON public.radares_radar",
    )
    _executar(
        schema_editor,
        """
        CREATE POLICY conta_isola ON public.radares_radar
        USING (conta_id::text = current_setting('app.conta_id', true))
        WITH CHECK (conta_id::text = current_setting('app.conta_id', true))
        """,
    )


def reverter_isolamento_do_radar(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        "DROP POLICY IF EXISTS conta_isola ON public.radares_radar",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.radares_radar NO FORCE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "ALTER TABLE public.radares_radar DISABLE ROW LEVEL SECURITY",
    )
    _executar(
        schema_editor,
        "REVOKE ALL ON TABLE public.radares_radar FROM rondimob_web, rondimob_worker",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imobiliaria', models.CharField(blank=True, default='', max_length=255)),
                ('cidade', models.CharField(max_length=64)),
                ('bairro', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(blank=True, default='', max_length=64)),
                ('preco_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quartos_minimos', models.PositiveIntegerField(blank=True, null=True)),
                ('vagas_minimas', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            aplicar_isolamento_do_radar,
            reverter_isolamento_do_radar,
        ),
    ]
