# Generated by Django 6.1.1 on 2026-09-30 20:26

import django.utils.timezone
import uuid
from django.db import migrations, models


def _executar(schema_editor, sql):
    schema_editor.execute(sql)


def conceder_dml(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        """
        GRANT SELECT, INSERT, UPDATE, DELETE
            ON TABLE public.coleta_falha
            TO rondimob_web, rondimob_worker
        """,
    )


def revogar_dml(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    _executar(
        schema_editor,
        "REVOKE ALL ON TABLE public.coleta_falha FROM rondimob_web, rondimob_worker",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0002_isolamento_da_conta"),
    ]

    operations = [
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonte', models.CharField(max_length=32)),
                ('mensagem', models.TextField()),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RunPython(conceder_dml, revogar_dml),
    ]
