# Generated by Django 6.1.1 on 2026-09-30 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _executar(schema_editor, sql):
    schema_editor.execute(sql)


def conceder_dml(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for tabela in ("anuncios_anuncio", "anuncios_preco"):
        _executar(
            schema_editor,
            f"""
            GRANT SELECT, INSERT, UPDATE, DELETE
                ON TABLE public.{tabela}
                TO rondimob_web, rondimob_worker
            """,
        )


def revogar_dml(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for tabela in ("anuncios_anuncio", "anuncios_preco"):
        _executar(
            schema_editor,
            f"REVOKE ALL ON TABLE public.{tabela} FROM rondimob_web, rondimob_worker",
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0002_isolamento_da_conta"),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonte', models.CharField(max_length=32)),
                ('identificador_externo', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField()),
                ('titulo', models.TextField(blank=True, default='')),
                ('endereco', models.TextField(blank=True, default='')),
                ('descricao', models.TextField(blank=True, default='')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('banheiros', models.IntegerField(blank=True, null=True)),
                ('vagas', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, default='', max_length=64)),
                ('bairro', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(blank=True, default='', max_length=64)),
                ('imobiliaria', models.CharField(blank=True, default='', max_length=255)),
                ('coletado_em', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('identificador_externo', ''), _negated=True), fields=('fonte', 'identificador_externo'), name='anuncio_fonte_e_id_externo'), models.UniqueConstraint(condition=models.Q(('identificador_externo', '')), fields=('fonte', 'url'), name='anuncio_fonte_e_url_sem_id')],
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('coletado_em', models.DateTimeField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='anuncios.anuncio')),
            ],
        ),
        migrations.RunPython(conceder_dml, revogar_dml),
    ]
